=== ProgVal/ManyGui/doc/src/minimal.dtd
<!ELEMENT document       (title, author?, date?, (para|codelisting)*, section*)>
<!ELEMENT section        (title, (para|codelisting)*, section*)>
<!ELEMENT title          (#PCDATA|emphasis|name|code|url|strong)*>
<!ELEMENT para           (#PCDATA|emphasis|name|code|url|strong|copyright|apiname|var)*>
<!ELEMENT emphasis       (#PCDATA|emphasis|name|code|url|strong)*>
<!ELEMENT strong         (#PCDATA|emphasis|name|code|url|strong)*>
<!ELEMENT apiname        (#PCDATA)*>
<!ELEMENT var            (#PCDATA)*>
<!ELEMENT codelisting    (line)*>
<!ELEMENT code           (#PCDATA)>
<!ELEMENT line           (#PCDATA|url)*>
<!ELEMENT name           (#PCDATA)>
<!ELEMENT url            (#PCDATA)>
<!ELEMENT copyright      EMPTY>

=== ProgVal/ManyGui/doc/src/anygui.xml
<?xml version="1.0"?>

<!DOCTYPE document SYSTEM "minimal.dtd" [
<!ENTITY shortversion            "0.1">
<!ENTITY longversion             "0.1b1">
<!ENTITY copy                    "<copyright/>">
<!ENTITY copyrightholders SYSTEM "copyrightholders.xml">
]>

<!-- TODO: - Add special tags for API reference
           - Add script for version
-->

<document version="&longversion;">

  <title>Anygui : Generic GUI for Python</title>

  <author>Magnus Lie Hetland</author>

  <date>...</date>

  <section>
    <title>Introduction</title>

    <para>The <name>Python</name> standard library currently does not
    contain any platform-independent GUI packages. It is the goal of
    the <name>Anygui</name> project to change this situation. There
    are many such packages available, but none has been defined as
    <emphasis>standard</emphasis>, so when writing GUI programs for
    <name>Python</name>, you cannot assume that your user has the
    right package installed.</para>

    <para>The problem is that declaring a GUI package as standard
    would be quite controversial. There are some packages that are
    quite commonly available, such as <name>Tkinter</name>; but it
    would not be practical to require all installations to include it,
    nor would it be desirable to require all <name>Python</name> GUI
    programs to use it, since there are many programmers who prefer
    other packages.</para>

    <para><name>Anygui</name> tries to solve this problem in a manner
    similar to the standard <code>anydbm</code> package. There is no
    need to choose <emphasis>one</emphasis> package at the expense of
    all others. Instead, <name>Anygui</name> gives generic access to
    several popular packages through a simple API, which makes it
    possible to write GUI applications that work with all these
    packages. Thus, one gets a platform-independent GUI module which
    is written entirely in <name>Python</name>.</para>

    <para>To get the latest <name>Anygui</name> distribution, or to
    get in touch with the developers, please visit the
    <name>Anygui</name> website:
    <url>http://www.anygui.org</url>.</para>

    <section>
      <title>Design Goals</title>

      <para><strong>A</strong>. <name>Anygui</name> should be an easy
      to use GUI package which may be used to create simple graphical
      programs, or which may serve as the basis for more complex
      application frameworks.</para>

      <para><strong>B</strong>. <name>Anygui</name> should be a pure
      <name>Python</name> package which serves as a front-end for as
      many as possible of the GUI packages available for
      <name>Python</name>, in a transparent manner.</para>

      <para><strong>C</strong>. <name>Anygui</name> should include
      functionality needed to perform most GUI tasks, but should
      remain as simple and basic as possible.</para>

    </section>

    <section>
      <title>Warning</title>

      <para>The <name>Anygui</name> API is currently very much in flux
      as the <name>Anygui</name> team keeps experimenting with
      it. Because of that, backwards incompatibilities may occur
      between releases. The current release should be regarded as a
      prototype.</para>

    </section>

  </section>

  <section>
    <title>Installation</title>
    
    <para>The <name>Anygui</name> package comes in the form of a
    <code>gzip</code> compressed <code>tar</code> archive. To install
    it you will first have to uncompress the archive. On
    <name>Windows</name> this can be done with <name>WinZip</name>. On
    the Mac, you can use <name>StuffIt Expander</name>. In
    <name>Unix</name>, first move to a directory where you'd like to
    put <name>Anygui</name>, and then do something like the
    following:</para>

    <codelisting>
      <line>foo:~/python$ tar xzvf anygui-&longversion;.tar.gz</line>
    </codelisting>

    <para>If your version of tar doesn't support the <code>z</code>
    switch, you can do something like this:</para>

    <codelisting>
      <line>foo:~/python$ zcat anygui-&longversion;.tar.gz | tar xvf</line>
    </codelisting>

    <para>Another possibility is:</para>

    <codelisting>
      <line>foo:~/python$ gunzip anygui-&longversion;.tar.gz</line>
    </codelisting>

    <para>No matter which version you choose, you should end up with a
    directory named <code>anygui-&longversion;</code>.</para>

    <section>
      <title>Running setup.py</title>
      
      <para>The simple way of installing <name>Anygui</name> is to use
      the installation script that's included in the
      distribution. This requires <name>Distutils</name>
      (<url>http://www.python.org/sigs/distutils-sig</url>), which is
      included in <name>Python</name> distributions from version
      2.0. To install the <name>Anygui</name> package in the default
      location, simply run the setup script with the
      <code>install</code> command:</para>

      <codelisting>
	<line>foo:~$ python setup.py install</line>
      </codelisting>

      <para>This will install <name>Anygui</name> in your standard
      <name>Python</name> directory structure. If you haven't
      installed <name>Python</name> yourself, you'll either have to
      have root access, or install it somewhere else. You can give a
      prefix with the <code>--prefix</code> option:</para>

      <codelisting>
	<line>foo:~$ python setup.py install --prefix=${HOME}/python</line>
      </codelisting>
    </section>

    <section>
      <title>Doing it Manually</title>

      <para>Since <name>Anygui</name> consists of only
      <name>Python</name> code, nothing needs to be compiled. And the
      only thing needed to install <name>Python</name> code is to
      ensure that the packages and modules are found by your
      <name>Python</name> interpreter. This may be as simple as
      including the <code>lib</code> directory of the
      <name>Anygui</name> distribution in your <code>PYTHONPATH</code>
      environment variable. In <code>bash</code>
      (<url>http://www.gnu.org/manual/bash/</url>), you could do
      something like this:</para>

      <codelisting>
	<line>foo:~$ export PYTHONPATH=$PYTHONPATH:/path/to/anygui/lib</line>
      </codelisting>

      <para>To make this permanent, you should put it in your
      <code>.bash_profile</code> file, or something equivalent. If you
      don't want to mess around with this, and already have a standard
      directory where you place your <name>Python</name> modules, you
      can simply copy (or move) the <code>lib/anygui</code>
      there, or possibly place a symlink in that directory to.</para>

    </section>

    <!--
    <section>
      <title>Distribution Layout</title>

      <para>[README, MAINTAINERS, LICENSE, etc.]</para>
    </section>
    -->

    <section>
      <title>Making Sure You Have a GUI Backend</title>

      <!-- document backend() function -->

      <para>Once you have <name>Anygui</name> installed, you'll want
      to make sure you have a usable GUI backend. This is easy to
      check: Simply start an interactive <name>Python</name>
      interpreter and try to execute the following:</para>

      <codelisting>
	<line>>>> from anygui import Application</line>
	<line>>>> Application()</line>
      </codelisting>

      <para>If this works, you should be all set for making GUI
      programs with <name>Anygui</name>. If it raises an exception,
      however, you will have to install a GUI
      package. <name>Anygui</name> currently supports the following
      packages:</para>

      <codelisting>
	<line>PythonWin  (mswgui)    <url>http://starship.python.net/crew/mhammond/win32</url></line>
	<line>Tkinter    (tkgui)     <url>http://www.python.org/topics/tkinter</url></line>
	<line>wxPython   (wxgui)     <url>http://www.wxpython.org</url></line>
	<line>Java Swing (javagui)   <url>http://www.jython.org</url></line>
	<line>PyGTK      (gtkgui)    <url>http://www.daa.com.au/~james/pygtk</url></line>
	<line>Bethon     (beosgui)   <url>http://www.bebits.com/app/1564</url></line>
	<line>Curses     (cursesgui) <url></url></line>
	<line>Plain text (textgui)   <url></url></line>
	<line>PyQt       (qtgui)     <url>http://www.thekompany.com/projects/pykde</url></line>
      </codelisting>

      <para>All of these backends are named with a short code (such as
      <code>msw</code> for <code>mswgui</code>, or PythonWin, and
      <code>wx</code> for <code>wxgui</code>, or
      <code>wxPython</code>). The code of the backend currently in use
      by a program can be retrieved with the <code>backend</code>
      function.</para>

      <para><strong>Note:</strong> The <name>BeOS</name> backen is not
      included in the current release (&longversion;), but is
      scheduled for inclusion in the final release
      (&shortversion;).</para>

      <!--
      Matt's fixes to Bethon:
      
      http://www.chariot.net.au/~jaq/matt/BWindow.dx
      http://www.chariot.net.au/~jaq/matt/BTextView.dx

      Also available at anygui.sf.net/files

      Rebuild Bethon with these.
      -->

      <para>Of these, <name>Tkinter</name> is compiled in by default
      in the <name>MS Windows</name> distribution of
      <name>Python</name> (available from
      <url>http://www.python.org</url>), <name>PythonWin</name> (as
      well as <name>Tkinter</name>) is included in the
      <name>ActiveState</name> distribution, <name>ActivePython</name>
      (available from <url>http://www.activestate.com</url>), and
      <name>Java Swing</name> is automatically available in
      <name>Jython</name>, the <name>Java</name> implementation of
      <name>Python</name>.</para>

      <para><strong>Note:</strong> <name>Anygui</name> (using
      <name>Tkinter</name>) works with <name>Mac OS</name> 9 with
      <name>Python Classic</name>. There seems to be some problems
      with <name>Python Carbon</name>.</para>
